<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-VNAPOA4" failures="2" tests="6" name="Test" time="54.313" errors="0" timestamp="2025-03-01T23:52:57 IST">
  <testcase classname="testCases.TC003_LoginwithDataProvider" name="login_with_data_providers" time="4.643"/>
  <testcase classname="testCases.TC003_LoginwithDataProvider" name="login_with_data_providers" time="2.179"/>
  <testcase classname="testCases.TC003_LoginwithDataProvider" name="login_with_data_providers" time="11.684"/>
  <testcase classname="testCases.TC003_LoginwithDataProvider" name="login_with_data_providers" time="1.495">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginwithDataProvider.login_with_data_providers(TC003_LoginwithDataProvider.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login_with_data_providers -->
  <testcase classname="testCases.TC003_LoginwithDataProvider" name="login_with_data_providers" time="10.207">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_LoginwithDataProvider.login_with_data_providers(TC003_LoginwithDataProvider.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- login_with_data_providers -->
  <testcase classname="testCases.TC002_LoginWithCreds" name="login_with_valid_creds" time="2.922"/>
</testsuite> <!-- Test -->
