<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-VNAPOA4" failures="2" tests="7" name="Test" time="95.898" errors="0" timestamp="2025-03-01T23:50:43 IST">
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="new_registration" time="14.014"/>
  <testcase classname="testCases.TC003_LoginwithDataProvider" name="login_with_data_providers" time="5.854"/>
  <testcase classname="testCases.TC003_LoginwithDataProvider" name="login_with_data_providers" time="3.944"/>
  <testcase classname="testCases.TC003_LoginwithDataProvider" name="login_with_data_providers" time="14.416"/>
  <testcase classname="testCases.TC003_LoginwithDataProvider" name="login_with_data_providers" time="2.516">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginwithDataProvider.login_with_data_providers(TC003_LoginwithDataProvider.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login_with_data_providers -->
  <testcase classname="testCases.TC003_LoginwithDataProvider" name="login_with_data_providers" time="10.377">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_LoginwithDataProvider.login_with_data_providers(TC003_LoginwithDataProvider.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login_with_data_providers -->
  <testcase classname="testCases.TC002_LoginWithCreds" name="login_with_valid_creds" time="4.271"/>
</testsuite> <!-- Test -->
